blank_issues_enabled: true
contact_links:
  - name: Get support on Discord
    url: https://discord.com/channels/1106106269837819914/1107004906696622102
    about: Get help from the maintainers on Discord
